---
title: "data_analysis_jcw"
author: "Michael Sambor"
date: "11/6/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
sample_sites <- unique(filter(ICPMS_tidy_example, site!="MB" , site!="")$site)
metals_analyzed <- unique(ICPMS_tidy_example$metal)


icpms_cal <- NULL
  for (unique_metal in metals_analyzed) {
  cal <- ICPMS_tidy_example %>%
  filter(type =="Cal1" | type == "Cal2" | type == "Cal3") %>%
  filter(metal == unique_metal) %>% 
  select(concentration, cps, rsd)
  
  w <- 1/(cal$cps*cal$rsd)^2
  model <- lm(cal$cps ~ cal$concentration, weights = w)

  slope <- model$coefficients[2]
  intercept <- model$coefficients[1]
  slope_std <- summary(model)$coefficients[2,2]
  intercept_std <- summary(model)$coefficients[1,2]

  plot(cal$cps ~ cal$concentration,
  xlab = paste("Concentration of ", unique_metal, "(ppb)"), 
  ylab = "Counts per second") +
  abline(model, col = "red") +
  title(paste("Calibration for", unique_metal))
  
  equation <- tibble(metal = unique_metal, slope, slope_std, intercept, intercept_std)
icpms_cal <- rbind(icpms_cal, equation)
}

icpms_cal
remove(equation,cal, slope, slope_std, intercept, intercept_std, w, model, unique_metal)


```

```{r}

#inputs: unique_site (as a character)
#outputs: concentration vector
sample_analysis <- function(unique_site){

concentration_data <- NULL
  for(unique_metal in metals_analyzed){
  sample <- filter(ICPMS_tidy_example, metal == unique_metal, site == unique_site)
  data <- NULL
  for(ID in sample$sample_key) {
  sample_data <- filter(sample, sample_key == ID)
  cal <- filter(icpms_cal, metal == unique_metal)
  #sample analysis
  m <- cal$slope
  b <- cal$intercept
  y <- sample_data$cps
  b_e <- cal$intercept_std
  m_e <- cal$slope_std
  x <- (y-b)/m 
  rsd <- sample_data$rsd
  cps <- sample_data$cps
  e_yb <- sqrt((rsd)^2 + (b_e)^2)
  #error in y-n from calibration
  yb <- cps-b
  e_x <- x*sqrt((e_yb/yb)^2 + (m_e/m)^2)
  #error in x from calibration
data <- rbind(data, data_frame(sample_key = ID, x, e_x))
if (unique_site != "MB") {
concentration_data <- data_frame(sample_key = sample_data$sample_key,
analyst = sample_data$analyst,
metal = unique_metal,
site = unique_site,
conc_dil = x,
conc_dil_error = e_x) %>%
rbind(concentration_data)
}
}
if (unique_site == "MB") {
x <- mean(data$x)
e_x <- sd(data$x)
concentration_data <- data_frame(metal = unique_metal,
site = unique_site,
conc_dil = x,
conc_dil_error = e_x) %>%
rbind(concentration_data)
}
}
return(concentration_data)
}

```

```{r}
#inputs: a function that runs a different function on each of the soil sample sites
#outputs: a data frame with the function outputs from each site
run_sites <- function(soil_function){
value <- NULL
for(sites in sample_sites) {
  site_value <- soil_function(sites)
value <- rbind(site_value, value)
}
return(value)
}
```

```{r}

MB <- sample_analysis("MB") #(ug/kg)
uncor_sample <- run_sites(sample_analysis)

MB
uncor_sample
```

```{r}
sample_data_mb <- NULL
for (unique_metal in metals_analyzed){
  MB_metal <- filter(MB, metal==unique_metal)
  sample_metal <- filter(uncor_sample, metal == unique_metal)
  conc_dil_blanked <- sample_metal$conc_dil-MB_metal$conc_dil
  #error propagation subtraction of MB
  conc_dil_blanked_error <- sqrt((sample_metal$conc_dil_error)^2 + (MB_metal$conc_dil_error)^2)
  
  sample_data_mb <- sample_metal %>%
    mutate(conc_dil_blanked, conc_dil_blanked_error)%>%
    rbind(sample_data_mb)
}
sample_data_mb
```

```{r}
#error propagation
vol_e <- 1
mass_e <- 0.001
dil_1010_e <- sqrt(1^2 + 10^2)
dil_e <- sqrt((dil_1010_e/1010)^2 + (1/10)^2) #error in 101 dilution factor
```

```{r}
sample_data <- merge(ICPMS_tidy_example, sample_data_mb) %>% 
  unique()%>%
  mutate(conc_blanked = conc_dil_blanked*(total_volume/1000)/(mass_of_soil/1000)*101,
         conc_blanked_error = conc_blanked*
           sqrt((conc_dil_blanked_error/conc_dil_blanked)^2 +
                  (dil_e/101)^2 + 
                  (mass_e/mass_of_soil)^2 +
                  (vol_e/total_volume)^2),
         conc_unblanked = conc_dil*(total_volume/1000)/(mass_of_soil/1000)*101,
         conc_blanked_error = conc_unblanked*
           sqrt((conc_dil_error/conc_dil)^2 + 
                  (dil_e/101)^2 +
                  (mass_e/mass_of_soil)^2))%>%
  select(-concentration, -type, -mass_of_soil, -total_volume, -cps, -rsd, -conc_dil_blanked, -conc_dil_blanked_error, -conc_dil, - conc_dil_error)
```

