---
title: "ICPMS_JWS_tidy"
author: "Michael Sambor"
date: "10/29/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readr)
```

```{r}
icpms_data <- read.csv("~/icpms_lab/JCW_ICPMS_lab/data/ICPMS_Data.csv", skip = 1, na="N/A")

sample_key <- read.csv("~/icpms_lab/JCW_ICPMS_lab/data/Sample_Key.csv", skip =0)
RSD_icpms <- icpms_data %>%
  select(Cr52 = CPS.RSD,
         Cr53 = CPS.RSD.1,
         As75 = CPS.RSD.2,
         Cd111 = CPS.RSD.3,
         Cd114 = CPS.RSD.4,
         Pb208 = CPS.RSD.5,
         Ge_RSD = CPS.RSD.7, 
         Sample.Key)%>%
  pivot_longer(1:6,
               names_to = "metal",
               values_to = "RSD")
icpms_tidy <- icpms_data %>%
  select(Cr52 = CPS,
         Cr53 = CPS.1,
         As75 = CPS.2,
         Cd111 = CPS.3,
         Cd114 = CPS.4,
         Pb208 = CPS.5,
         Ge72 = CPS.7,
         Sample.Key) %>%
  pivot_longer(1:6, names_to = "metal",
               values_to = "CPS") %>%
  mutate(RSD = RSD_icpms$RSD/RSD_icpms$Ge_RSD,
         CPS=CPS/Ge72)%>%
  select(-Ge72)

all(RSD_icpms$Sample.Key==icpms_tidy$Sample.Key, RSD_icpms$metal==icpms_tidy$metal)

icpms_merged <- merge(icpms_tidy, sample_key)
 write.csv(icpms_merged, file = "~/icpms_lab/JCW_ICPMS_lab/data/icpms_tidy.csv")


```

```{r, warning= FALSE}
rm(list=setdiff(ls(), "icpms_merged"))
```

```{r}

aa_data_import <- read_csv("~/icpms_lab/JCW_ICPMS_lab/data/AA_Data.csv", skip = 4)


aa_data <- aa_data_import[!(aa_data_import$`Sample Key`=="Sample Blank" | aa_data_import$`Sample Key`=="check10"),]

metal <- c("Cr", "Cr", "Cr", "Cr", "Cr", "Cr", "Cr", "Cr", "Cr", "Cr", "Cr", "Cr", "Cr", "Cr", "Cr", "Cr", "Cr", "Cr", "Cr", "Cr", "Cr", "Cr", "Cr", "Cr", "Cr", "Cr", "Cr", "Cr", "Cr", "Cr", "Cr", "Cr", "Cr", "Cr", "Cr", "Cr", "Cr", "Cr", "Cr", "Cr", "Cr", "Cr", "Cr", "Cr", "Cr", "Cr", "Cr", "Cr", "Cr", "Cr", "Cr", "Cr", "Cr", "Cr", "Cr", "Cr", "Cr", "Cr", "Cr", "Cr", "Cr", "Cr", "Cr", "Cr", "Cr")


aa_newlabel <- aa_data_import
aa_newlabel$`Sample Key` <- gsub("Sample Blank", 0, aa_newlabel$`Sample Key`)
aa_newlabel$`Sample Key` <- gsub("check10", 100, aa_newlabel$`Sample Key`)

aa_newlabel["Metal"] <- metal



 write.csv(aa_newlabel, file = "~/icpms_lab/JCW_ICPMS_lab/data/aa_tidy.csv")

```

```{r}

```


